### PR TITLE
Feature/l10n

### PR DESCRIPTION
**Pull request by fxbenard**
Trying to fix merge issue

### CODE REVIEW

**Comment by samikeijonen** [comment]
Hmmm, same here. I'll try to manually merge this. Never done it before so not sure how it's gonna work out.

**Comment by fxbenard** [comment]
Damn

Just grab the 2 French files and add them manually to your master. I didn't change anything else

**Comment by samikeijonen** [comment]
Well, it's a good test for me to use command line:) Need to learn it more anyways.

**Comment by samikeijonen** [comment]
I think I got it now!

**Pull request merged**
